name: "Test GitHub Action"
run-name: test-github-action
env:
  SBOM_FILE: "./tests/files/sbom_sec_observe.cdx.json"
on:
  workflow_call:

jobs:
  analyze-sbom:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false
      - name: Test Action Default License
        uses: ./
        id: analyze-sbom-default-license
        with:
          SBOM_PATH: ${{ env.SBOM_FILE }}
          BREAK_ENABLED: false
      - name: Test Action External License
        uses: ./
        id: analyze-sbom-external-license
        with:
          SBOM_PATH: ${{ env.SBOM_FILE }}
          BREAK_ENABLED: false
          LICENSE_POLICY_PATH: "/github/workspace/tests/files/mw_license_policy.json"
          IGNORE_PKG_TYPES: ""
      - name: Upload SBOM evaluation artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: evaluated_sbom
          path: ${{ github.workspace }}/evaluated_sbom.csv
          if-no-files-found: error
