name: Test published GitHub Action
run-name: test
env:
  SBOM_PATH: "./tests/files/sbom_sec_observe.cdx.json"
on:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: "3.14"

      - name: Create venv and install pytest
        run: |
          python -m venv .venv
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
          python -m pip install --upgrade pip
          pip install pytest
          pip install tabulate

      - name: Unit tests license-policy-check
        run: cd tools/license-policy-check/testing && pytest test_check_usage_policy.py -q && cd ../../..

      - uses: MaibornWolff/purl-patrol@d6f7c24159eaf338f06be54138eee7ee51ea423b # main
        with:
          SBOM_PATH: ${{env.SBOM_PATH}}
          BREAK_ENABLED: false
